<?php
/**
 * BatchPaymentSummary
 *
 * PHP version 8.1
 *
 * @package  SynergiTech\Iplicit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Iplicit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Iplicit\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use SynergiTech\Iplicit\ObjectSerializer;

/**
 * BatchPaymentSummary Class Doc Comment
 *
 * @package  SynergiTech\Iplicit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class BatchPaymentSummary implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'BatchPaymentSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'string',
        'batchPaymentTypeId' => 'string',
        'batchNo' => 'string',
        'description' => 'string',
        'status' => 'int',
        'statusList' => 'string[]',
        'legalEntityId' => 'string',
        'bankAccountId' => 'string',
        'paymentDate' => '\DateTime',
        'paymentMethodId' => 'string',
        'periodId' => 'string',
        'bankCurrency' => 'string',
        'bankCurrencyAmount' => 'float',
        'bankCurrencyRate' => 'float',
        'bankRef' => 'string',
        'lastModified' => '\DateTime',
        'lastModifiedBy' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => 'uuid',
        'batchPaymentTypeId' => 'uuid',
        'batchNo' => null,
        'description' => null,
        'status' => 'int64',
        'statusList' => null,
        'legalEntityId' => 'uuid',
        'bankAccountId' => 'uuid',
        'paymentDate' => 'date-time',
        'paymentMethodId' => 'uuid',
        'periodId' => 'uuid',
        'bankCurrency' => null,
        'bankCurrencyAmount' => 'double',
        'bankCurrencyRate' => 'double',
        'bankRef' => null,
        'lastModified' => 'date-time',
        'lastModifiedBy' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'batchPaymentTypeId' => false,
        'batchNo' => true,
        'description' => true,
        'status' => false,
        'statusList' => true,
        'legalEntityId' => false,
        'bankAccountId' => false,
        'paymentDate' => false,
        'paymentMethodId' => false,
        'periodId' => false,
        'bankCurrency' => true,
        'bankCurrencyAmount' => false,
        'bankCurrencyRate' => false,
        'bankRef' => true,
        'lastModified' => true,
        'lastModifiedBy' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'batchPaymentTypeId' => 'batchPaymentTypeId',
        'batchNo' => 'batchNo',
        'description' => 'description',
        'status' => 'status',
        'statusList' => 'statusList',
        'legalEntityId' => 'legalEntityId',
        'bankAccountId' => 'bankAccountId',
        'paymentDate' => 'paymentDate',
        'paymentMethodId' => 'paymentMethodId',
        'periodId' => 'periodId',
        'bankCurrency' => 'bankCurrency',
        'bankCurrencyAmount' => 'bankCurrencyAmount',
        'bankCurrencyRate' => 'bankCurrencyRate',
        'bankRef' => 'bankRef',
        'lastModified' => 'lastModified',
        'lastModifiedBy' => 'lastModifiedBy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'batchPaymentTypeId' => 'setBatchPaymentTypeId',
        'batchNo' => 'setBatchNo',
        'description' => 'setDescription',
        'status' => 'setStatus',
        'statusList' => 'setStatusList',
        'legalEntityId' => 'setLegalEntityId',
        'bankAccountId' => 'setBankAccountId',
        'paymentDate' => 'setPaymentDate',
        'paymentMethodId' => 'setPaymentMethodId',
        'periodId' => 'setPeriodId',
        'bankCurrency' => 'setBankCurrency',
        'bankCurrencyAmount' => 'setBankCurrencyAmount',
        'bankCurrencyRate' => 'setBankCurrencyRate',
        'bankRef' => 'setBankRef',
        'lastModified' => 'setLastModified',
        'lastModifiedBy' => 'setLastModifiedBy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'batchPaymentTypeId' => 'getBatchPaymentTypeId',
        'batchNo' => 'getBatchNo',
        'description' => 'getDescription',
        'status' => 'getStatus',
        'statusList' => 'getStatusList',
        'legalEntityId' => 'getLegalEntityId',
        'bankAccountId' => 'getBankAccountId',
        'paymentDate' => 'getPaymentDate',
        'paymentMethodId' => 'getPaymentMethodId',
        'periodId' => 'getPeriodId',
        'bankCurrency' => 'getBankCurrency',
        'bankCurrencyAmount' => 'getBankCurrencyAmount',
        'bankCurrencyRate' => 'getBankCurrencyRate',
        'bankRef' => 'getBankRef',
        'lastModified' => 'getLastModified',
        'lastModifiedBy' => 'getLastModifiedBy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('batchPaymentTypeId', $data ?? [], null);
        $this->setIfExists('batchNo', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('statusList', $data ?? [], null);
        $this->setIfExists('legalEntityId', $data ?? [], null);
        $this->setIfExists('bankAccountId', $data ?? [], null);
        $this->setIfExists('paymentDate', $data ?? [], null);
        $this->setIfExists('paymentMethodId', $data ?? [], null);
        $this->setIfExists('periodId', $data ?? [], null);
        $this->setIfExists('bankCurrency', $data ?? [], null);
        $this->setIfExists('bankCurrencyAmount', $data ?? [], null);
        $this->setIfExists('bankCurrencyRate', $data ?? [], null);
        $this->setIfExists('bankRef', $data ?? [], null);
        $this->setIfExists('lastModified', $data ?? [], null);
        $this->setIfExists('lastModifiedBy', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id The batch payment unique id
     *
     * @return $this
     */
    public function setId(?string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets batchPaymentTypeId
     *
     * @return string|null
     */
    public function getBatchPaymentTypeId(): ?string
    {
        return $this->container['batchPaymentTypeId'];
    }

    /**
     * Sets batchPaymentTypeId
     *
     * @param string|null $batchPaymentTypeId The batch payment unique id
     *
     * @return $this
     */
    public function setBatchPaymentTypeId(?string $batchPaymentTypeId): static
    {
        if (is_null($batchPaymentTypeId)) {
            throw new InvalidArgumentException('non-nullable batchPaymentTypeId cannot be null');
        }
        $this->container['batchPaymentTypeId'] = $batchPaymentTypeId;

        return $this;
    }

    /**
     * Gets batchNo
     *
     * @return string|null
     */
    public function getBatchNo(): ?string
    {
        return $this->container['batchNo'];
    }

    /**
     * Sets batchNo
     *
     * @param string|null $batchNo The batch payment batch number
     *
     * @return $this
     */
    public function setBatchNo(?string $batchNo): static
    {
        if (is_null($batchNo)) {
            array_push($this->openAPINullablesSetToNull, 'batchNo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('batchNo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['batchNo'] = $batchNo;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The batch payment description
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets status
     *
     * @return int|null
     */
    public function getStatus(): ?int
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param int|null $status The batch payment status
     *
     * @return $this
     */
    public function setStatus(?int $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets statusList
     *
     * @return string[]|null
     */
    public function getStatusList(): ?array
    {
        return $this->container['statusList'];
    }

    /**
     * Sets statusList
     *
     * @param string[]|null $statusList The batch payment status list
     *
     * @return $this
     */
    public function setStatusList(?array $statusList): static
    {
        if (is_null($statusList)) {
            array_push($this->openAPINullablesSetToNull, 'statusList');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('statusList', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['statusList'] = $statusList;

        return $this;
    }

    /**
     * Gets legalEntityId
     *
     * @return string|null
     */
    public function getLegalEntityId(): ?string
    {
        return $this->container['legalEntityId'];
    }

    /**
     * Sets legalEntityId
     *
     * @param string|null $legalEntityId The batch payment legal entity id
     *
     * @return $this
     */
    public function setLegalEntityId(?string $legalEntityId): static
    {
        if (is_null($legalEntityId)) {
            throw new InvalidArgumentException('non-nullable legalEntityId cannot be null');
        }
        $this->container['legalEntityId'] = $legalEntityId;

        return $this;
    }

    /**
     * Gets bankAccountId
     *
     * @return string|null
     */
    public function getBankAccountId(): ?string
    {
        return $this->container['bankAccountId'];
    }

    /**
     * Sets bankAccountId
     *
     * @param string|null $bankAccountId The batch payment bank account id
     *
     * @return $this
     */
    public function setBankAccountId(?string $bankAccountId): static
    {
        if (is_null($bankAccountId)) {
            throw new InvalidArgumentException('non-nullable bankAccountId cannot be null');
        }
        $this->container['bankAccountId'] = $bankAccountId;

        return $this;
    }

    /**
     * Gets paymentDate
     *
     * @return \DateTime|null
     */
    public function getPaymentDate(): ?\DateTime
    {
        return $this->container['paymentDate'];
    }

    /**
     * Sets paymentDate
     *
     * @param \DateTime|null $paymentDate The batch payment  date
     *
     * @return $this
     */
    public function setPaymentDate(?\DateTime $paymentDate): static
    {
        if (is_null($paymentDate)) {
            throw new InvalidArgumentException('non-nullable paymentDate cannot be null');
        }
        $this->container['paymentDate'] = $paymentDate;

        return $this;
    }

    /**
     * Gets paymentMethodId
     *
     * @return string|null
     */
    public function getPaymentMethodId(): ?string
    {
        return $this->container['paymentMethodId'];
    }

    /**
     * Sets paymentMethodId
     *
     * @param string|null $paymentMethodId The batch payment method id
     *
     * @return $this
     */
    public function setPaymentMethodId(?string $paymentMethodId): static
    {
        if (is_null($paymentMethodId)) {
            throw new InvalidArgumentException('non-nullable paymentMethodId cannot be null');
        }
        $this->container['paymentMethodId'] = $paymentMethodId;

        return $this;
    }

    /**
     * Gets periodId
     *
     * @return string|null
     */
    public function getPeriodId(): ?string
    {
        return $this->container['periodId'];
    }

    /**
     * Sets periodId
     *
     * @param string|null $periodId The batch payment period id
     *
     * @return $this
     */
    public function setPeriodId(?string $periodId): static
    {
        if (is_null($periodId)) {
            throw new InvalidArgumentException('non-nullable periodId cannot be null');
        }
        $this->container['periodId'] = $periodId;

        return $this;
    }

    /**
     * Gets bankCurrency
     *
     * @return string|null
     */
    public function getBankCurrency(): ?string
    {
        return $this->container['bankCurrency'];
    }

    /**
     * Sets bankCurrency
     *
     * @param string|null $bankCurrency The batch payment bank currency
     *
     * @return $this
     */
    public function setBankCurrency(?string $bankCurrency): static
    {
        if (is_null($bankCurrency)) {
            array_push($this->openAPINullablesSetToNull, 'bankCurrency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bankCurrency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bankCurrency'] = $bankCurrency;

        return $this;
    }

    /**
     * Gets bankCurrencyAmount
     *
     * @return float|null
     */
    public function getBankCurrencyAmount(): ?float
    {
        return $this->container['bankCurrencyAmount'];
    }

    /**
     * Sets bankCurrencyAmount
     *
     * @param float|null $bankCurrencyAmount The batch payment bank currency amount
     *
     * @return $this
     */
    public function setBankCurrencyAmount(?float $bankCurrencyAmount): static
    {
        if (is_null($bankCurrencyAmount)) {
            throw new InvalidArgumentException('non-nullable bankCurrencyAmount cannot be null');
        }
        $this->container['bankCurrencyAmount'] = $bankCurrencyAmount;

        return $this;
    }

    /**
     * Gets bankCurrencyRate
     *
     * @return float|null
     */
    public function getBankCurrencyRate(): ?float
    {
        return $this->container['bankCurrencyRate'];
    }

    /**
     * Sets bankCurrencyRate
     *
     * @param float|null $bankCurrencyRate The batch payment bank currency rate
     *
     * @return $this
     */
    public function setBankCurrencyRate(?float $bankCurrencyRate): static
    {
        if (is_null($bankCurrencyRate)) {
            throw new InvalidArgumentException('non-nullable bankCurrencyRate cannot be null');
        }
        $this->container['bankCurrencyRate'] = $bankCurrencyRate;

        return $this;
    }

    /**
     * Gets bankRef
     *
     * @return string|null
     */
    public function getBankRef(): ?string
    {
        return $this->container['bankRef'];
    }

    /**
     * Sets bankRef
     *
     * @param string|null $bankRef The batch payment bank reference
     *
     * @return $this
     */
    public function setBankRef(?string $bankRef): static
    {
        if (is_null($bankRef)) {
            array_push($this->openAPINullablesSetToNull, 'bankRef');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bankRef', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bankRef'] = $bankRef;

        return $this;
    }

    /**
     * Gets lastModified
     *
     * @return \DateTime|null
     */
    public function getLastModified(): ?\DateTime
    {
        return $this->container['lastModified'];
    }

    /**
     * Sets lastModified
     *
     * @param \DateTime|null $lastModified The date and time this item has been last modified
     *
     * @return $this
     */
    public function setLastModified(?\DateTime $lastModified): static
    {
        if (is_null($lastModified)) {
            array_push($this->openAPINullablesSetToNull, 'lastModified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lastModified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lastModified'] = $lastModified;

        return $this;
    }

    /**
     * Gets lastModifiedBy
     *
     * @return string|null
     */
    public function getLastModifiedBy(): ?string
    {
        return $this->container['lastModifiedBy'];
    }

    /**
     * Sets lastModifiedBy
     *
     * @param string|null $lastModifiedBy The user that last modified this item. See `UserAccount` catalog.
     *
     * @return $this
     */
    public function setLastModifiedBy(?string $lastModifiedBy): static
    {
        if (is_null($lastModifiedBy)) {
            array_push($this->openAPINullablesSetToNull, 'lastModifiedBy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lastModifiedBy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lastModifiedBy'] = $lastModifiedBy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


