<?php
/**
 * ProjectCreate
 *
 * PHP version 8.1
 *
 * @package  SynergiTech\Iplicit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Iplicit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Iplicit\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use SynergiTech\Iplicit\ObjectSerializer;

/**
 * ProjectCreate Class Doc Comment
 *
 * @package  SynergiTech\Iplicit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ProjectCreate implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ProjectCreate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'code' => 'string',
        'intRef' => 'string',
        'description' => 'string',
        'dateFrom' => '\DateTime',
        'dateTo' => '\DateTime',
        'projectGroupId' => 'string',
        'legalEntityId' => 'string',
        'contactAccountId' => 'string',
        'responsibleResourceId' => 'string',
        'parentProjectId' => 'string',
        'allowTimesheets' => 'bool',
        'allowTasks' => 'bool',
        'isParent' => 'bool',
        'hasAddress' => 'bool',
        'hasResources' => 'bool',
        'hasMilestones' => 'bool',
        'address' => '\SynergiTech\Iplicit\Model\ProjectAddressCreate',
        'availability' => '\SynergiTech\Iplicit\Model\ProjectAvailabilityCreate[]',
        'milestones' => '\SynergiTech\Iplicit\Model\ProjectMilestoneCreate[]',
        'ext' => 'array<string,mixed>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'code' => null,
        'intRef' => null,
        'description' => null,
        'dateFrom' => 'date-time',
        'dateTo' => 'date-time',
        'projectGroupId' => null,
        'legalEntityId' => null,
        'contactAccountId' => null,
        'responsibleResourceId' => null,
        'parentProjectId' => null,
        'allowTimesheets' => null,
        'allowTasks' => null,
        'isParent' => null,
        'hasAddress' => null,
        'hasResources' => null,
        'hasMilestones' => null,
        'address' => null,
        'availability' => null,
        'milestones' => null,
        'ext' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'code' => true,
        'intRef' => true,
        'description' => false,
        'dateFrom' => true,
        'dateTo' => true,
        'projectGroupId' => true,
        'legalEntityId' => true,
        'contactAccountId' => true,
        'responsibleResourceId' => true,
        'parentProjectId' => true,
        'allowTimesheets' => true,
        'allowTasks' => true,
        'isParent' => true,
        'hasAddress' => true,
        'hasResources' => true,
        'hasMilestones' => true,
        'address' => false,
        'availability' => true,
        'milestones' => true,
        'ext' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'code' => 'code',
        'intRef' => 'intRef',
        'description' => 'description',
        'dateFrom' => 'dateFrom',
        'dateTo' => 'dateTo',
        'projectGroupId' => 'projectGroupId',
        'legalEntityId' => 'legalEntityId',
        'contactAccountId' => 'contactAccountId',
        'responsibleResourceId' => 'responsibleResourceId',
        'parentProjectId' => 'parentProjectId',
        'allowTimesheets' => 'allowTimesheets',
        'allowTasks' => 'allowTasks',
        'isParent' => 'isParent',
        'hasAddress' => 'hasAddress',
        'hasResources' => 'hasResources',
        'hasMilestones' => 'hasMilestones',
        'address' => 'address',
        'availability' => 'availability',
        'milestones' => 'milestones',
        'ext' => 'ext'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'code' => 'setCode',
        'intRef' => 'setIntRef',
        'description' => 'setDescription',
        'dateFrom' => 'setDateFrom',
        'dateTo' => 'setDateTo',
        'projectGroupId' => 'setProjectGroupId',
        'legalEntityId' => 'setLegalEntityId',
        'contactAccountId' => 'setContactAccountId',
        'responsibleResourceId' => 'setResponsibleResourceId',
        'parentProjectId' => 'setParentProjectId',
        'allowTimesheets' => 'setAllowTimesheets',
        'allowTasks' => 'setAllowTasks',
        'isParent' => 'setIsParent',
        'hasAddress' => 'setHasAddress',
        'hasResources' => 'setHasResources',
        'hasMilestones' => 'setHasMilestones',
        'address' => 'setAddress',
        'availability' => 'setAvailability',
        'milestones' => 'setMilestones',
        'ext' => 'setExt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'code' => 'getCode',
        'intRef' => 'getIntRef',
        'description' => 'getDescription',
        'dateFrom' => 'getDateFrom',
        'dateTo' => 'getDateTo',
        'projectGroupId' => 'getProjectGroupId',
        'legalEntityId' => 'getLegalEntityId',
        'contactAccountId' => 'getContactAccountId',
        'responsibleResourceId' => 'getResponsibleResourceId',
        'parentProjectId' => 'getParentProjectId',
        'allowTimesheets' => 'getAllowTimesheets',
        'allowTasks' => 'getAllowTasks',
        'isParent' => 'getIsParent',
        'hasAddress' => 'getHasAddress',
        'hasResources' => 'getHasResources',
        'hasMilestones' => 'getHasMilestones',
        'address' => 'getAddress',
        'availability' => 'getAvailability',
        'milestones' => 'getMilestones',
        'ext' => 'getExt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('intRef', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('dateFrom', $data ?? [], null);
        $this->setIfExists('dateTo', $data ?? [], null);
        $this->setIfExists('projectGroupId', $data ?? [], null);
        $this->setIfExists('legalEntityId', $data ?? [], null);
        $this->setIfExists('contactAccountId', $data ?? [], null);
        $this->setIfExists('responsibleResourceId', $data ?? [], null);
        $this->setIfExists('parentProjectId', $data ?? [], null);
        $this->setIfExists('allowTimesheets', $data ?? [], null);
        $this->setIfExists('allowTasks', $data ?? [], null);
        $this->setIfExists('isParent', $data ?? [], null);
        $this->setIfExists('hasAddress', $data ?? [], null);
        $this->setIfExists('hasResources', $data ?? [], null);
        $this->setIfExists('hasMilestones', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('availability', $data ?? [], null);
        $this->setIfExists('milestones', $data ?? [], null);
        $this->setIfExists('ext', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['code']) && (mb_strlen($this->container['code']) > 50)) {
            $invalidProperties[] = "invalid value for 'code', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['intRef']) && (mb_strlen($this->container['intRef']) > 50)) {
            $invalidProperties[] = "invalid value for 'intRef', the character length must be smaller than or equal to 50.";
        }

        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ((mb_strlen($this->container['description']) > 100)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['description']) < 1)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['projectGroupId']) && (mb_strlen($this->container['projectGroupId']) > 50)) {
            $invalidProperties[] = "invalid value for 'projectGroupId', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['legalEntityId']) && (mb_strlen($this->container['legalEntityId']) > 50)) {
            $invalidProperties[] = "invalid value for 'legalEntityId', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['contactAccountId']) && (mb_strlen($this->container['contactAccountId']) > 50)) {
            $invalidProperties[] = "invalid value for 'contactAccountId', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['responsibleResourceId']) && (mb_strlen($this->container['responsibleResourceId']) > 50)) {
            $invalidProperties[] = "invalid value for 'responsibleResourceId', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['parentProjectId']) && (mb_strlen($this->container['parentProjectId']) > 50)) {
            $invalidProperties[] = "invalid value for 'parentProjectId', the character length must be smaller than or equal to 50.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode(): ?string
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code The project code
     *
     * @return $this
     */
    public function setCode(?string $code): static
    {
        if (is_null($code)) {
            array_push($this->openAPINullablesSetToNull, 'code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($code) && (mb_strlen($code) > 50)) {
            throw new InvalidArgumentException('invalid length for $code when calling ProjectCreate., must be smaller than or equal to 50.');
        }

        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets intRef
     *
     * @return string|null
     */
    public function getIntRef(): ?string
    {
        return $this->container['intRef'];
    }

    /**
     * Sets intRef
     *
     * @param string|null $intRef Optional interface reference. If provided, it must be unique. <a href=\"https://docs.iplicit.com/dev/guide/identifiers/index.html\">Learn more</a>
     *
     * @return $this
     */
    public function setIntRef(?string $intRef): static
    {
        if (is_null($intRef)) {
            array_push($this->openAPINullablesSetToNull, 'intRef');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('intRef', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($intRef) && (mb_strlen($intRef) > 50)) {
            throw new InvalidArgumentException('invalid length for $intRef when calling ProjectCreate., must be smaller than or equal to 50.');
        }

        $this->container['intRef'] = $intRef;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription(): string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description The project description
     *
     * @return $this
     */
    public function setDescription(string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 100)) {
            throw new InvalidArgumentException('invalid length for $description when calling ProjectCreate., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($description) < 1)) {
            throw new InvalidArgumentException('invalid length for $description when calling ProjectCreate., must be bigger than or equal to 1.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets dateFrom
     *
     * @return \DateTime|null
     */
    public function getDateFrom(): ?\DateTime
    {
        return $this->container['dateFrom'];
    }

    /**
     * Sets dateFrom
     *
     * @param \DateTime|null $dateFrom The project from date
     *
     * @return $this
     */
    public function setDateFrom(?\DateTime $dateFrom): static
    {
        if (is_null($dateFrom)) {
            array_push($this->openAPINullablesSetToNull, 'dateFrom');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dateFrom', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dateFrom'] = $dateFrom;

        return $this;
    }

    /**
     * Gets dateTo
     *
     * @return \DateTime|null
     */
    public function getDateTo(): ?\DateTime
    {
        return $this->container['dateTo'];
    }

    /**
     * Sets dateTo
     *
     * @param \DateTime|null $dateTo The project to date
     *
     * @return $this
     */
    public function setDateTo(?\DateTime $dateTo): static
    {
        if (is_null($dateTo)) {
            array_push($this->openAPINullablesSetToNull, 'dateTo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dateTo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dateTo'] = $dateTo;

        return $this;
    }

    /**
     * Gets projectGroupId
     *
     * @return string|null
     */
    public function getProjectGroupId(): ?string
    {
        return $this->container['projectGroupId'];
    }

    /**
     * Sets projectGroupId
     *
     * @param string|null $projectGroupId The project group id
     *
     * @return $this
     */
    public function setProjectGroupId(?string $projectGroupId): static
    {
        if (is_null($projectGroupId)) {
            array_push($this->openAPINullablesSetToNull, 'projectGroupId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('projectGroupId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($projectGroupId) && (mb_strlen($projectGroupId) > 50)) {
            throw new InvalidArgumentException('invalid length for $projectGroupId when calling ProjectCreate., must be smaller than or equal to 50.');
        }

        $this->container['projectGroupId'] = $projectGroupId;

        return $this;
    }

    /**
     * Gets legalEntityId
     *
     * @return string|null
     */
    public function getLegalEntityId(): ?string
    {
        return $this->container['legalEntityId'];
    }

    /**
     * Sets legalEntityId
     *
     * @param string|null $legalEntityId The project legal entity id
     *
     * @return $this
     */
    public function setLegalEntityId(?string $legalEntityId): static
    {
        if (is_null($legalEntityId)) {
            array_push($this->openAPINullablesSetToNull, 'legalEntityId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('legalEntityId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($legalEntityId) && (mb_strlen($legalEntityId) > 50)) {
            throw new InvalidArgumentException('invalid length for $legalEntityId when calling ProjectCreate., must be smaller than or equal to 50.');
        }

        $this->container['legalEntityId'] = $legalEntityId;

        return $this;
    }

    /**
     * Gets contactAccountId
     *
     * @return string|null
     */
    public function getContactAccountId(): ?string
    {
        return $this->container['contactAccountId'];
    }

    /**
     * Sets contactAccountId
     *
     * @param string|null $contactAccountId The project contact account id
     *
     * @return $this
     */
    public function setContactAccountId(?string $contactAccountId): static
    {
        if (is_null($contactAccountId)) {
            array_push($this->openAPINullablesSetToNull, 'contactAccountId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('contactAccountId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($contactAccountId) && (mb_strlen($contactAccountId) > 50)) {
            throw new InvalidArgumentException('invalid length for $contactAccountId when calling ProjectCreate., must be smaller than or equal to 50.');
        }

        $this->container['contactAccountId'] = $contactAccountId;

        return $this;
    }

    /**
     * Gets responsibleResourceId
     *
     * @return string|null
     */
    public function getResponsibleResourceId(): ?string
    {
        return $this->container['responsibleResourceId'];
    }

    /**
     * Sets responsibleResourceId
     *
     * @param string|null $responsibleResourceId The project responsible resource id
     *
     * @return $this
     */
    public function setResponsibleResourceId(?string $responsibleResourceId): static
    {
        if (is_null($responsibleResourceId)) {
            array_push($this->openAPINullablesSetToNull, 'responsibleResourceId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('responsibleResourceId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($responsibleResourceId) && (mb_strlen($responsibleResourceId) > 50)) {
            throw new InvalidArgumentException('invalid length for $responsibleResourceId when calling ProjectCreate., must be smaller than or equal to 50.');
        }

        $this->container['responsibleResourceId'] = $responsibleResourceId;

        return $this;
    }

    /**
     * Gets parentProjectId
     *
     * @return string|null
     */
    public function getParentProjectId(): ?string
    {
        return $this->container['parentProjectId'];
    }

    /**
     * Sets parentProjectId
     *
     * @param string|null $parentProjectId The project parent project id
     *
     * @return $this
     */
    public function setParentProjectId(?string $parentProjectId): static
    {
        if (is_null($parentProjectId)) {
            array_push($this->openAPINullablesSetToNull, 'parentProjectId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('parentProjectId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($parentProjectId) && (mb_strlen($parentProjectId) > 50)) {
            throw new InvalidArgumentException('invalid length for $parentProjectId when calling ProjectCreate., must be smaller than or equal to 50.');
        }

        $this->container['parentProjectId'] = $parentProjectId;

        return $this;
    }

    /**
     * Gets allowTimesheets
     *
     * @return bool|null
     */
    public function getAllowTimesheets(): ?bool
    {
        return $this->container['allowTimesheets'];
    }

    /**
     * Sets allowTimesheets
     *
     * @param bool|null $allowTimesheets The project allow timesheets flag
     *
     * @return $this
     */
    public function setAllowTimesheets(?bool $allowTimesheets): static
    {
        if (is_null($allowTimesheets)) {
            array_push($this->openAPINullablesSetToNull, 'allowTimesheets');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('allowTimesheets', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['allowTimesheets'] = $allowTimesheets;

        return $this;
    }

    /**
     * Gets allowTasks
     *
     * @return bool|null
     */
    public function getAllowTasks(): ?bool
    {
        return $this->container['allowTasks'];
    }

    /**
     * Sets allowTasks
     *
     * @param bool|null $allowTasks The project allow tasks flag
     *
     * @return $this
     */
    public function setAllowTasks(?bool $allowTasks): static
    {
        if (is_null($allowTasks)) {
            array_push($this->openAPINullablesSetToNull, 'allowTasks');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('allowTasks', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['allowTasks'] = $allowTasks;

        return $this;
    }

    /**
     * Gets isParent
     *
     * @return bool|null
     */
    public function getIsParent(): ?bool
    {
        return $this->container['isParent'];
    }

    /**
     * Sets isParent
     *
     * @param bool|null $isParent The project is parent flag
     *
     * @return $this
     */
    public function setIsParent(?bool $isParent): static
    {
        if (is_null($isParent)) {
            array_push($this->openAPINullablesSetToNull, 'isParent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('isParent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['isParent'] = $isParent;

        return $this;
    }

    /**
     * Gets hasAddress
     *
     * @return bool|null
     */
    public function getHasAddress(): ?bool
    {
        return $this->container['hasAddress'];
    }

    /**
     * Sets hasAddress
     *
     * @param bool|null $hasAddress The project has address flag
     *
     * @return $this
     */
    public function setHasAddress(?bool $hasAddress): static
    {
        if (is_null($hasAddress)) {
            array_push($this->openAPINullablesSetToNull, 'hasAddress');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hasAddress', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hasAddress'] = $hasAddress;

        return $this;
    }

    /**
     * Gets hasResources
     *
     * @return bool|null
     */
    public function getHasResources(): ?bool
    {
        return $this->container['hasResources'];
    }

    /**
     * Sets hasResources
     *
     * @param bool|null $hasResources The project has resources flag
     *
     * @return $this
     */
    public function setHasResources(?bool $hasResources): static
    {
        if (is_null($hasResources)) {
            array_push($this->openAPINullablesSetToNull, 'hasResources');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hasResources', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hasResources'] = $hasResources;

        return $this;
    }

    /**
     * Gets hasMilestones
     *
     * @return bool|null
     */
    public function getHasMilestones(): ?bool
    {
        return $this->container['hasMilestones'];
    }

    /**
     * Sets hasMilestones
     *
     * @param bool|null $hasMilestones The project has milestones flag
     *
     * @return $this
     */
    public function setHasMilestones(?bool $hasMilestones): static
    {
        if (is_null($hasMilestones)) {
            array_push($this->openAPINullablesSetToNull, 'hasMilestones');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hasMilestones', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hasMilestones'] = $hasMilestones;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \SynergiTech\Iplicit\Model\ProjectAddressCreate|null
     */
    public function getAddress(): ?\SynergiTech\Iplicit\Model\ProjectAddressCreate
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \SynergiTech\Iplicit\Model\ProjectAddressCreate|null $address address
     *
     * @return $this
     */
    public function setAddress(?\SynergiTech\Iplicit\Model\ProjectAddressCreate $address): static
    {
        if (is_null($address)) {
            throw new InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets availability
     *
     * @return \SynergiTech\Iplicit\Model\ProjectAvailabilityCreate[]|null
     */
    public function getAvailability(): ?array
    {
        return $this->container['availability'];
    }

    /**
     * Sets availability
     *
     * @param \SynergiTech\Iplicit\Model\ProjectAvailabilityCreate[]|null $availability The project resource availability
     *
     * @return $this
     */
    public function setAvailability(?array $availability): static
    {
        if (is_null($availability)) {
            array_push($this->openAPINullablesSetToNull, 'availability');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('availability', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['availability'] = $availability;

        return $this;
    }

    /**
     * Gets milestones
     *
     * @return \SynergiTech\Iplicit\Model\ProjectMilestoneCreate[]|null
     */
    public function getMilestones(): ?array
    {
        return $this->container['milestones'];
    }

    /**
     * Sets milestones
     *
     * @param \SynergiTech\Iplicit\Model\ProjectMilestoneCreate[]|null $milestones The project milestones
     *
     * @return $this
     */
    public function setMilestones(?array $milestones): static
    {
        if (is_null($milestones)) {
            array_push($this->openAPINullablesSetToNull, 'milestones');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('milestones', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['milestones'] = $milestones;

        return $this;
    }

    /**
     * Gets ext
     *
     * @return array<string,mixed>|null
     */
    public function getExt(): ?array
    {
        return $this->container['ext'];
    }

    /**
     * Sets ext
     *
     * @param array<string,mixed>|null $ext The project custom fields
     *
     * @return $this
     */
    public function setExt(?array $ext): static
    {
        if (is_null($ext)) {
            array_push($this->openAPINullablesSetToNull, 'ext');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ext', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ext'] = $ext;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


