<?php
/**
 * DocumentAttachmentApi
 * PHP version 8.1
 *
 * @package  SynergiTech\Iplicit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Iplicit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Iplicit\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use SynergiTech\Iplicit\ApiException;
use SynergiTech\Iplicit\Configuration;
use SynergiTech\Iplicit\HeaderSelector;
use SynergiTech\Iplicit\ObjectSerializer;

/**
 * DocumentAttachmentApi Class Doc Comment
 *
 * @package  SynergiTech\Iplicit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentAttachmentApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createDocumentAttachment' => [
            'multipart/form-data',
        ],
        'getDocumentAttachmentGroups' => [
            'application/json',
        ],
        'getDocumentAttachmentsInGroup' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation createDocumentAttachment
     *
     * Create a new attachment on a sepcified document.
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \SplFileObject $file Attachment file information (required)
     * @param  string|null $description Attachment description (optional)
     * @param  \DateTime|null $documentDate Attachment document date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDocumentAttachment'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return string
     */
    public function createDocumentAttachment(
        string $docRef,
        string $attachmentGroupId,
        string $domain,
        \SplFileObject $file,
        ?string $description = null,
        ?\DateTime $documentDate = null,
        string $contentType = self::contentTypes['createDocumentAttachment'][0]
    ): string
    {
        list($response) = $this->createDocumentAttachmentWithHttpInfo($docRef, $attachmentGroupId, $domain, $file, $description, $documentDate, $contentType);
        return $response;
    }

    /**
     * Operation createDocumentAttachmentWithHttpInfo
     *
     * Create a new attachment on a sepcified document.
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \SplFileObject $file Attachment file information (required)
     * @param  string|null $description Attachment description (optional)
     * @param  \DateTime|null $documentDate Attachment document date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDocumentAttachment'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function createDocumentAttachmentWithHttpInfo(
        string $docRef,
        string $attachmentGroupId,
        string $domain,
        \SplFileObject $file,
        ?string $description = null,
        ?\DateTime $documentDate = null,
        string $contentType = self::contentTypes['createDocumentAttachment'][0]
    ): array
    {
        $request = $this->createDocumentAttachmentRequest($docRef, $attachmentGroupId, $domain, $file, $description, $documentDate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if (in_array('string', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createDocumentAttachmentAsync
     *
     * Create a new attachment on a sepcified document.
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \SplFileObject $file Attachment file information (required)
     * @param  string|null $description Attachment description (optional)
     * @param  \DateTime|null $documentDate Attachment document date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDocumentAttachment'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createDocumentAttachmentAsync(
        string $docRef,
        string $attachmentGroupId,
        string $domain,
        \SplFileObject $file,
        ?string $description = null,
        ?\DateTime $documentDate = null,
        string $contentType = self::contentTypes['createDocumentAttachment'][0]
    ): PromiseInterface
    {
        return $this->createDocumentAttachmentAsyncWithHttpInfo($docRef, $attachmentGroupId, $domain, $file, $description, $documentDate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createDocumentAttachmentAsyncWithHttpInfo
     *
     * Create a new attachment on a sepcified document.
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \SplFileObject $file Attachment file information (required)
     * @param  string|null $description Attachment description (optional)
     * @param  \DateTime|null $documentDate Attachment document date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDocumentAttachment'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createDocumentAttachmentAsyncWithHttpInfo(
        $docRef,
        $attachmentGroupId,
        $domain,
        $file,
        $description = null,
        $documentDate = null,
        string $contentType = self::contentTypes['createDocumentAttachment'][0]
    ): PromiseInterface
    {
        $returnType = 'string';
        $request = $this->createDocumentAttachmentRequest($docRef, $attachmentGroupId, $domain, $file, $description, $documentDate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createDocumentAttachment'
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \SplFileObject $file Attachment file information (required)
     * @param  string|null $description Attachment description (optional)
     * @param  \DateTime|null $documentDate Attachment document date (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDocumentAttachment'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createDocumentAttachmentRequest(
        $docRef,
        $attachmentGroupId,
        $domain,
        $file,
        $description = null,
        $documentDate = null,
        string $contentType = self::contentTypes['createDocumentAttachment'][0]
    ): Request
    {

        // verify the required parameter 'docRef' is set
        if ($docRef === null || (is_array($docRef) && count($docRef) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $docRef when calling createDocumentAttachment'
            );
        }

        // verify the required parameter 'attachmentGroupId' is set
        if ($attachmentGroupId === null || (is_array($attachmentGroupId) && count($attachmentGroupId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $attachmentGroupId when calling createDocumentAttachment'
            );
        }

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $domain when calling createDocumentAttachment'
            );
        }

        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $file when calling createDocumentAttachment'
            );
        }

        if ($description !== null && strlen($description) > 250) {
            throw new InvalidArgumentException('invalid length for "$description" when calling DocumentAttachmentApi.createDocumentAttachment, must be smaller than or equal to 250.');
        }



        $resourcePath = '/api/Document/{docRef}/AttachmentGroup/{attachmentGroupId}/Attachment';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($domain !== null) {
            $headerParams['Domain'] = ObjectSerializer::toHeaderValue($domain);
        }

        // path params
        if ($docRef !== null) {
            $resourcePath = str_replace(
                '{' . 'docRef' . '}',
                ObjectSerializer::toPathValue($docRef),
                $resourcePath
            );
        }
        // path params
        if ($attachmentGroupId !== null) {
            $resourcePath = str_replace(
                '{' . 'attachmentGroupId' . '}',
                ObjectSerializer::toPathValue($attachmentGroupId),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['File'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['File'][] = $paramFile instanceof \Psr\Http\Message\StreamInterface
                    ? $paramFile
                    : \GuzzleHttp\Psr7\Utils::tryFopen(
                        ObjectSerializer::toFormValue($paramFile),
                        'rb'
                    );
            }
        }
        // form params
        if ($description !== null) {
            $formParams['Description'] = ObjectSerializer::toFormValue($description);
        }
        // form params
        if ($documentDate !== null) {
            $formParams['DocumentDate'] = ObjectSerializer::toFormValue($documentDate);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        if (!empty($this->config->getDomainHeader())) {
            $headers['Domain'] = $this->config->getDomainHeader();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDocumentAttachmentGroups
     *
     * Get a list of attachment groups defined on a specified document type.
     *
     * @param  string $docTypeRef Id or code of the document type (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentGroups'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Iplicit\Model\AttachmentGroupRead[]
     */
    public function getDocumentAttachmentGroups(
        string $docTypeRef,
        string $domain,
        string $contentType = self::contentTypes['getDocumentAttachmentGroups'][0]
    ): array
    {
        list($response) = $this->getDocumentAttachmentGroupsWithHttpInfo($docTypeRef, $domain, $contentType);
        return $response;
    }

    /**
     * Operation getDocumentAttachmentGroupsWithHttpInfo
     *
     * Get a list of attachment groups defined on a specified document type.
     *
     * @param  string $docTypeRef Id or code of the document type (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentGroups'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Iplicit\Model\AttachmentGroupRead[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getDocumentAttachmentGroupsWithHttpInfo(
        string $docTypeRef,
        string $domain,
        string $contentType = self::contentTypes['getDocumentAttachmentGroups'][0]
    ): array
    {
        $request = $this->getDocumentAttachmentGroupsRequest($docTypeRef, $domain, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if (in_array('\SynergiTech\Iplicit\Model\AttachmentGroupRead[]', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Iplicit\Model\AttachmentGroupRead[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Iplicit\Model\AttachmentGroupRead[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SynergiTech\Iplicit\Model\AttachmentGroupRead[]';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Iplicit\Model\AttachmentGroupRead[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getDocumentAttachmentGroupsAsync
     *
     * Get a list of attachment groups defined on a specified document type.
     *
     * @param  string $docTypeRef Id or code of the document type (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentGroups'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getDocumentAttachmentGroupsAsync(
        string $docTypeRef,
        string $domain,
        string $contentType = self::contentTypes['getDocumentAttachmentGroups'][0]
    ): PromiseInterface
    {
        return $this->getDocumentAttachmentGroupsAsyncWithHttpInfo($docTypeRef, $domain, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDocumentAttachmentGroupsAsyncWithHttpInfo
     *
     * Get a list of attachment groups defined on a specified document type.
     *
     * @param  string $docTypeRef Id or code of the document type (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentGroups'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getDocumentAttachmentGroupsAsyncWithHttpInfo(
        $docTypeRef,
        $domain,
        string $contentType = self::contentTypes['getDocumentAttachmentGroups'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Iplicit\Model\AttachmentGroupRead[]';
        $request = $this->getDocumentAttachmentGroupsRequest($docTypeRef, $domain, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDocumentAttachmentGroups'
     *
     * @param  string $docTypeRef Id or code of the document type (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentGroups'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDocumentAttachmentGroupsRequest(
        $docTypeRef,
        $domain,
        string $contentType = self::contentTypes['getDocumentAttachmentGroups'][0]
    ): Request
    {

        // verify the required parameter 'docTypeRef' is set
        if ($docTypeRef === null || (is_array($docTypeRef) && count($docTypeRef) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $docTypeRef when calling getDocumentAttachmentGroups'
            );
        }

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $domain when calling getDocumentAttachmentGroups'
            );
        }


        $resourcePath = '/api/DocumentType/{docTypeRef}/AttachmentGroup';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($domain !== null) {
            $headerParams['Domain'] = ObjectSerializer::toHeaderValue($domain);
        }

        // path params
        if ($docTypeRef !== null) {
            $resourcePath = str_replace(
                '{' . 'docTypeRef' . '}',
                ObjectSerializer::toPathValue($docTypeRef),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        if (!empty($this->config->getDomainHeader())) {
            $headers['Domain'] = $this->config->getDomainHeader();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDocumentAttachmentsInGroup
     *
     * Get a list of attachments in an attachment group on a specified document with a search filter.
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \DateTime|null $createdFrom Filter attachments created after a specific date time (optional)
     * @param  string|null $fileName Filter attachments with a specific file name (optional)
     * @param  int|null $take The number of records to return (optional, default to 100)
     * @param  int|null $skip The number of records to skip (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentsInGroup'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Iplicit\Model\AttachmentRead[]
     */
    public function getDocumentAttachmentsInGroup(
        string $docRef,
        string $attachmentGroupId,
        string $domain,
        ?\DateTime $createdFrom = null,
        ?string $fileName = null,
        ?int $take = 100,
        ?int $skip = 0,
        string $contentType = self::contentTypes['getDocumentAttachmentsInGroup'][0]
    ): array
    {
        list($response) = $this->getDocumentAttachmentsInGroupWithHttpInfo($docRef, $attachmentGroupId, $domain, $createdFrom, $fileName, $take, $skip, $contentType);
        return $response;
    }

    /**
     * Operation getDocumentAttachmentsInGroupWithHttpInfo
     *
     * Get a list of attachments in an attachment group on a specified document with a search filter.
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \DateTime|null $createdFrom Filter attachments created after a specific date time (optional)
     * @param  string|null $fileName Filter attachments with a specific file name (optional)
     * @param  int|null $take The number of records to return (optional, default to 100)
     * @param  int|null $skip The number of records to skip (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentsInGroup'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Iplicit\Model\AttachmentRead[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getDocumentAttachmentsInGroupWithHttpInfo(
        string $docRef,
        string $attachmentGroupId,
        string $domain,
        ?\DateTime $createdFrom = null,
        ?string $fileName = null,
        ?int $take = 100,
        ?int $skip = 0,
        string $contentType = self::contentTypes['getDocumentAttachmentsInGroup'][0]
    ): array
    {
        $request = $this->getDocumentAttachmentsInGroupRequest($docRef, $attachmentGroupId, $domain, $createdFrom, $fileName, $take, $skip, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if (in_array('\SynergiTech\Iplicit\Model\AttachmentRead[]', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Iplicit\Model\AttachmentRead[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Iplicit\Model\AttachmentRead[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SynergiTech\Iplicit\Model\AttachmentRead[]';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Iplicit\Model\AttachmentRead[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getDocumentAttachmentsInGroupAsync
     *
     * Get a list of attachments in an attachment group on a specified document with a search filter.
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \DateTime|null $createdFrom Filter attachments created after a specific date time (optional)
     * @param  string|null $fileName Filter attachments with a specific file name (optional)
     * @param  int|null $take The number of records to return (optional, default to 100)
     * @param  int|null $skip The number of records to skip (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentsInGroup'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getDocumentAttachmentsInGroupAsync(
        string $docRef,
        string $attachmentGroupId,
        string $domain,
        ?\DateTime $createdFrom = null,
        ?string $fileName = null,
        ?int $take = 100,
        ?int $skip = 0,
        string $contentType = self::contentTypes['getDocumentAttachmentsInGroup'][0]
    ): PromiseInterface
    {
        return $this->getDocumentAttachmentsInGroupAsyncWithHttpInfo($docRef, $attachmentGroupId, $domain, $createdFrom, $fileName, $take, $skip, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDocumentAttachmentsInGroupAsyncWithHttpInfo
     *
     * Get a list of attachments in an attachment group on a specified document with a search filter.
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \DateTime|null $createdFrom Filter attachments created after a specific date time (optional)
     * @param  string|null $fileName Filter attachments with a specific file name (optional)
     * @param  int|null $take The number of records to return (optional, default to 100)
     * @param  int|null $skip The number of records to skip (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentsInGroup'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getDocumentAttachmentsInGroupAsyncWithHttpInfo(
        $docRef,
        $attachmentGroupId,
        $domain,
        $createdFrom = null,
        $fileName = null,
        $take = 100,
        $skip = 0,
        string $contentType = self::contentTypes['getDocumentAttachmentsInGroup'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Iplicit\Model\AttachmentRead[]';
        $request = $this->getDocumentAttachmentsInGroupRequest($docRef, $attachmentGroupId, $domain, $createdFrom, $fileName, $take, $skip, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDocumentAttachmentsInGroup'
     *
     * @param  string $docRef Id, document number or &lt;a href&#x3D;\&quot;https://docs.iplicit.com/dev/guide/identifiers/index.html\&quot;&gt;internal reference&lt;/a&gt; of the document to search (required)
     * @param  string $attachmentGroupId Id of the attachment group. Use special value &#39;other&#39; to get attachments without a group. (required)
     * @param  string $domain Your assigned domain name. Required for all API requests. (required)
     * @param  \DateTime|null $createdFrom Filter attachments created after a specific date time (optional)
     * @param  string|null $fileName Filter attachments with a specific file name (optional)
     * @param  int|null $take The number of records to return (optional, default to 100)
     * @param  int|null $skip The number of records to skip (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDocumentAttachmentsInGroup'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDocumentAttachmentsInGroupRequest(
        $docRef,
        $attachmentGroupId,
        $domain,
        $createdFrom = null,
        $fileName = null,
        $take = 100,
        $skip = 0,
        string $contentType = self::contentTypes['getDocumentAttachmentsInGroup'][0]
    ): Request
    {

        // verify the required parameter 'docRef' is set
        if ($docRef === null || (is_array($docRef) && count($docRef) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $docRef when calling getDocumentAttachmentsInGroup'
            );
        }

        // verify the required parameter 'attachmentGroupId' is set
        if ($attachmentGroupId === null || (is_array($attachmentGroupId) && count($attachmentGroupId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $attachmentGroupId when calling getDocumentAttachmentsInGroup'
            );
        }

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $domain when calling getDocumentAttachmentsInGroup'
            );
        }






        $resourcePath = '/api/Document/{docRef}/AttachmentGroup/{attachmentGroupId}/Attachment';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $createdFrom,
            'createdFrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fileName,
            'fileName', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $take,
            'take', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            'skip', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($domain !== null) {
            $headerParams['Domain'] = ObjectSerializer::toHeaderValue($domain);
        }

        // path params
        if ($docRef !== null) {
            $resourcePath = str_replace(
                '{' . 'docRef' . '}',
                ObjectSerializer::toPathValue($docRef),
                $resourcePath
            );
        }
        // path params
        if ($attachmentGroupId !== null) {
            $resourcePath = str_replace(
                '{' . 'attachmentGroupId' . '}',
                ObjectSerializer::toPathValue($attachmentGroupId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        if (!empty($this->config->getDomainHeader())) {
            $headers['Domain'] = $this->config->getDomainHeader();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
